/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library lmidi
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include "lmidi/In.h"
#include "lmidi/Out.h"
#include "/Users/gaspard/git/lmidi/src/bind_headers/Fifo.h"

using namespace lk;
using namespace lmidi;

extern "C" {
int luaopen_lmidi_In(lua_State *L);
int luaopen_lmidi_Out(lua_State *L);
}

// --=============================================== FUNCTIONS
static const struct luaL_Reg lmidi_functions[] = {
  { NULL, NULL},
};


extern "C" int luaopen_lmidi_core(lua_State *L) {
  lua_newtable(L);
  // <lib>
  dub::fregister(L, lmidi_functions);
  // <lib>

  luaopen_lmidi_In(L);
  // <lmidi.In>
  lua_setfield(L, -2, "In");
  
  luaopen_lmidi_Out(L);
  // <lmidi.Out>
  lua_setfield(L, -2, "Out");
  
  // <lib>
  return 1;
}
